### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by Het-Shah** [a-ws-m/unlockNN#19]
Hi @a-ws-m! This will be an issue for my review for your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/3700). 

Pros - 
- The API is straightforward for the end-user to use. 

Cons - 
- The library seems to have ~1000 lines of actual code (1165). This begs the question about the substantial scholarly effort. 
- The paper lacks details about the library itself. It is unclear as to how the package is structured and what are the key functionalities. 
- It would be advantageous if you could make some basic ablations and provide their results. I am unaware of the datasets, but you can try on the smallest dataset and provide results. 

Feel free to comment on these. I would be more than happy to discuss the same.

**Comment by a-ws-m** [comment]
The benchmarks are complete and I've reported the results for a few models with different hyperparameters in the appropriate [results directory](https://github.com/a-ws-m/unlockNN/tree/joss-review/benchmarking/matbench/results).

**Comment by Het-Shah** [comment]
Great! everything seems fine to me now. I have completed the checklist on the JOSS thread and will cross-post this comment there as well.
