### ISSUE TITLE
Aragon network unlock

### ISSUE THREAD

**Issue by matthewmelissa049** [a-ws-m/unlockNN#41]

**Comment by a-ws-m** [comment]
Hi, there's no information here. Please explain the issue or feature request.

**Comment by matthewmelissa049** [comment]
I mean,whenever I try to active esim on my iPhone
It’s not working
I get to seee message like my fone is locked by Argon USA

**Comment by a-ws-m** [comment]
I'm sorry to hear that! However, I think you might be in the wrong place: this is a repository about a chemistry software package and I'm afraid it has nothing to do with mobile networks.

**Comment by a-ws-m** [comment]
This is probably whst you're looking for: https://support.apple.com/en-us/HT201328
